# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PLPlayerKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PLPlayerKitTest

  pod 'PLPlayerKit'

  target 'PLPlayerKitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PLPlayerKitTestUITests' do
    # Pods for testing
  end

end
